"""v5

Revision ID: 7238cb804bc4
Revises: 4e4b9dccb628
Create Date: 2022-06-22 15:02:34.987922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7238cb804bc4'
down_revision = '4e4b9dccb628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('button',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('project_uuid', sa.String(length=36), nullable=True),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_uuid'], ['project.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('button')
    # ### end Alembic commands ###
