"""v1

Revision ID: c45c67f7ad04
Revises: 
Create Date: 2021-11-16 23:35:46.410318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45c67f7ad04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('web', sa.String(length=256), nullable=True),
    sa.Column('github', sa.String(length=256), nullable=True),
    sa.Column('a', sa.Text(), nullable=True),
    sa.Column('b', sa.Text(), nullable=True),
    sa.Column('c', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    # ### end Alembic commands ###
